name = "linguo"
account_id = "957e76f879966209b57d6f31e977f764"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[[d1_databases]]
binding = "DB"
database_name = "linguo-db"
database_id = "735a5964-e9cf-4103-aba0-871338966175"
