name = "linguo"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[[d1_databases]]
binding = "DB"
database_name = "linguo-db"
database_id = "67f37eee-6c67-40f9-b687-ba59565e5c7a"
